[package]
name = "wasmer/wasm-opt"
version = "0.1190000.1"

[[module]]
name = "wasm-opt"
source = "out/bin/wasm-opt"

[[command]]
name = "wasm-opt"
module = "wasm-opt"
runner = "https://webc.org/runner/wasi"
